builders:
  - script
triggers:
  cron: "@weekly"
slack:
  room: "devops-builds"
clean_workspace: true
build_in_docker:
  image: docker.sunet.se/sunet/docker-jenkins-node-job

extra_jobs:
  - name: docker-mdq-browser
    builders:
      - docker
    docker_name: docker-mdq-browser
    managed_scripts:
      - docker_build_prep.sh
      - docker_tag.sh
    triggers:
      github_push: false
    upstream:
      - mdq-browser

script:
  - env PATH=/usr/local/bin:$PATH make
